# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 18:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAction',
            fields=[
                ('id_act', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ech_act', models.IntegerField(blank=True, null=True, verbose_name='Échéancier')),
                ('int_act', models.CharField(blank=True, max_length=255, null=True, verbose_name='Intitulé')),
                ('mont_ht_act', models.FloatField(blank=True, null=True, verbose_name='Montant HT')),
                ('mont_ttc_act', models.FloatField(blank=True, null=True, verbose_name='Montant TTC')),
                ('num_act', models.IntegerField(help_text="Veuillez renseigner l'index de la lettre de l'alphabet. Exemple : 1 -> a, 2 -> b, 3 -> c...", verbose_name='Numéro')),
            ],
            options={
                'ordering': ['id_ss_axe__id_axe__id_progr__int_progr', 'id_ss_axe__id_axe__num_axe', 'id_ss_axe__num_ss_axe', 'num_act'],
                'db_table': 't_action',
                'verbose_name': 'Action',
            },
        ),
        migrations.CreateModel(
            name='TArretesDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chem_pj_arr', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_lim_encl_trav_arr', models.DateField(blank=True, null=True)),
                ('dt_sign_arr', models.DateField(blank=True, null=True)),
                ('num_arr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_arretes_dossier',
            },
        ),
        migrations.CreateModel(
            name='TAvancement',
            fields=[
                ('id_av', models.AutoField(primary_key=True, serialize=False)),
                ('int_av', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_av'],
                'verbose_name_plural': "Avancements d'un dossier",
                'db_table': 't_avancement',
                'verbose_name': "Avancement d'un dossier",
            },
        ),
        migrations.CreateModel(
            name='TAvenant',
            fields=[
                ('id_aven', models.AutoField(primary_key=True, serialize=False)),
                ('dt_aven', models.DateField(blank=True, null=True)),
                ('int_aven', models.CharField(max_length=255)),
                ('mont_ht_aven', models.FloatField()),
                ('mont_ttc_aven', models.FloatField()),
            ],
            options={
                'db_table': 't_avenant',
            },
        ),
        migrations.CreateModel(
            name='TAvisCp',
            fields=[
                ('id_av_cp', models.AutoField(primary_key=True, serialize=False)),
                ('int_av_cp', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_av_cp'],
                'verbose_name_plural': 'Avis du comité de programmation',
                'db_table': 't_avis_cp',
                'verbose_name': 'Avis du comité de programmation',
            },
        ),
        migrations.CreateModel(
            name='TAxe',
            fields=[
                ('id_axe', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('int_axe', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('num_axe', models.IntegerField(verbose_name='Numéro')),
            ],
            options={
                'ordering': ['id_progr__int_progr', 'num_axe'],
                'db_table': 't_axe',
                'verbose_name': 'Axe',
            },
        ),
        migrations.CreateModel(
            name='TCommune',
            fields=[
                ('num_comm', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('n_comm', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['n_comm', 'num_comm'],
                'db_table': 't_commune',
            },
        ),
        migrations.CreateModel(
            name='TCommunesCp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_communes_cp',
            },
        ),
        migrations.CreateModel(
            name='TCp',
            fields=[
                ('cp_comm', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('code_comm', models.ManyToManyField(through='app.TCommunesCp', to='app.TCommune')),
            ],
            options={
                'ordering': ['cp_comm'],
                'db_table': 't_cp',
            },
        ),
        migrations.CreateModel(
            name='TDemandeVersement',
            fields=[
                ('id_ddv', models.AutoField(primary_key=True, serialize=False)),
                ('chem_pj_ddv', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_ddv', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_ddv', models.DateField(blank=True, null=True)),
                ('dt_vers_ddv', models.DateField(blank=True, null=True)),
                ('int_ddv', models.CharField(max_length=255)),
                ('mont_ht_ddv', models.FloatField()),
                ('mont_ht_verse_ddv', models.FloatField()),
                ('mont_ttc_ddv', models.FloatField()),
                ('mont_ttc_verse_ddv', models.FloatField()),
            ],
            options={
                'db_table': 't_demande_versement',
            },
        ),
        migrations.CreateModel(
            name='TDepartement',
            fields=[
                ('num_dep', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Numéro')),
                ('n_dep', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'ordering': ['num_dep'],
                'db_table': 't_departement',
            },
        ),
        migrations.CreateModel(
            name='TDossier',
            fields=[
                ('id_doss', models.AutoField(primary_key=True, serialize=False)),
                ('chem_dds_doss', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_doss', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_regl_doss', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_av_cp_doss', models.DateField(blank=True, null=True)),
                ('dt_delib_moa_doss', models.DateField(blank=True, null=True)),
                ('dt_int_doss', models.DateField()),
                ('ld_doss', models.CharField(max_length=255)),
                ('mont_ht_doss', models.FloatField()),
                ('mont_ttc_doss', models.FloatField()),
                ('terr_doss', models.CharField(max_length=255)),
                ('num_doss', models.CharField(max_length=255, unique=True)),
                ('num_act', models.IntegerField(blank=True, null=True)),
                ('num_axe', models.IntegerField(blank=True, null=True)),
                ('num_ss_axe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['num_doss'],
                'db_table': 't_dossier',
                'verbose_name': 'Dossier',
            },
        ),
        migrations.CreateModel(
            name='TDossierGeom',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom_lin', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=2154)),
                ('geom_pct', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2154)),
                ('geom_pol', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=2154)),
            ],
            options={
                'db_table': 't_dossier_geom',
            },
        ),
        migrations.CreateModel(
            name='TDroit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_ecr', models.BooleanField()),
                ('en_lect', models.BooleanField()),
            ],
            options={
                'db_table': 't_droit',
                'verbose_name': 'Droit',
            },
        ),
        migrations.CreateModel(
            name='TFacture',
            fields=[
                ('id_fact', models.AutoField(primary_key=True, serialize=False)),
                ('chem_pj_fact', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_fact', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_mand_moa_fact', models.DateField(blank=True, null=True)),
                ('dt_rec_fact', models.DateField(blank=True, null=True)),
                ('mont_ht_fact', models.FloatField()),
                ('mont_ttc_fact', models.FloatField()),
                ('num_bord', models.CharField(blank=True, max_length=255, null=True)),
                ('num_fact', models.CharField(max_length=255)),
                ('num_mandat', models.CharField(blank=True, max_length=255, null=True)),
                ('suivi_fact', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_facture',
            },
        ),
        migrations.CreateModel(
            name='TFacturesDemandeVersement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ddv', models.ForeignKey(db_column='id_ddv', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDemandeVersement')),
                ('id_fact', models.ForeignKey(db_column='id_fact', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TFacture')),
            ],
            options={
                'db_table': 't_factures_demande_versement',
            },
        ),
        migrations.CreateModel(
            name='TFamille',
            fields=[
                ('id_fam', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 't_famille',
            },
        ),
        migrations.CreateModel(
            name='TFinancement',
            fields=[
                ('id_fin', models.AutoField(primary_key=True, serialize=False)),
                ('chem_pj_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_deb_elig_fin', models.DateField(blank=True, null=True)),
                ('dt_lim_deb_oper_fin', models.DateField(blank=True, null=True)),
                ('dt_lim_prem_ac_fin', models.DateField(blank=True, null=True)),
                ('duree_pror_fin', models.IntegerField(default=0)),
                ('duree_valid_fin', models.IntegerField()),
                ('mont_ht_elig_fin', models.FloatField(blank=True, null=True)),
                ('mont_ht_part_fin', models.FloatField()),
                ('mont_ttc_elig_fin', models.FloatField(blank=True, null=True)),
                ('mont_ttc_part_fin', models.FloatField()),
                ('num_arr_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('pourc_elig_fin', models.FloatField(blank=True, null=True)),
                ('pourc_real_fin', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_financement',
            },
        ),
        migrations.CreateModel(
            name='TInstanceConcertation',
            fields=[
                ('id_inst_conc', models.AutoField(primary_key=True, serialize=False)),
                ('int_inst_conc', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_inst_conc'],
                'verbose_name_plural': 'Instances de concertation',
                'db_table': 't_instance_concertation',
                'verbose_name': 'Instance de concertation',
            },
        ),
        migrations.CreateModel(
            name='TNatureDossier',
            fields=[
                ('id_nat_doss', models.AutoField(primary_key=True, serialize=False)),
                ('int_nat_doss', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_nat_doss'],
                'verbose_name_plural': 'Natures de dossiers',
                'db_table': 't_nature_dossier',
                'verbose_name': 'Nature de dossier',
            },
        ),
        migrations.CreateModel(
            name='TNaturePrestation',
            fields=[
                ('id_nat_prest', models.AutoField(primary_key=True, serialize=False)),
                ('int_nat_prest', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_nat_prest'],
                'verbose_name_plural': 'Natures de prestations',
                'db_table': 't_nature_prestation',
                'verbose_name': 'Nature de prestation',
            },
        ),
        migrations.CreateModel(
            name='TOrganisme',
            fields=[
                ('id_org', models.AutoField(primary_key=True, serialize=False)),
                ('adr_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse (ligne 1)')),
                ('bp_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Boîte postale')),
                ('cedex_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cedex')),
                ('comm_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Commentaire')),
                ('compl_adr_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse (ligne 2)')),
                ('cont_org', models.CharField(blank=True, max_length=255, null=True)),
                ('courr_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse électronique')),
                ('cp_org', models.CharField(blank=True, max_length=5, null=True, verbose_name='Code postal')),
                ('n_org', models.CharField(max_length=255, verbose_name='Nom')),
                ('port_org', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone portable')),
                ('site_web_org', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site web')),
                ('tel_org', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone')),
            ],
            options={
                'ordering': ['n_org'],
                'db_table': 't_organisme',
                'verbose_name': 'Organisme',
            },
        ),
        migrations.CreateModel(
            name='TPaiementPremierAcompte',
            fields=[
                ('id_paiem_prem_ac', models.AutoField(primary_key=True, serialize=False)),
                ('int_paiem_prem_ac', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_paiem_prem_ac'],
                'verbose_name_plural': 'Paiements du premier acompte',
                'db_table': 't_paiement_premier_acompte',
                'verbose_name': 'Paiement du premier acompte',
            },
        ),
        migrations.CreateModel(
            name='TPeriodePriseVuePhoto',
            fields=[
                ('id_ppv_ph', models.AutoField(primary_key=True, serialize=False)),
                ('int_ppv_ph', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('ordre_ppv_ph', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordre_ppv_ph'],
                'verbose_name_plural': 'Périodes de prise de vue',
                'db_table': 't_periode_prise_vue_photo',
                'verbose_name': 'Période de prise de vue',
            },
        ),
        migrations.CreateModel(
            name='TPhoto',
            fields=[
                ('id_ph', models.AutoField(primary_key=True, serialize=False)),
                ('chem_ph', models.CharField(max_length=255)),
                ('descr_ph', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_pv_ph', models.DateField(blank=True, null=True)),
                ('geom_ph', models.TextField(blank=True, null=True)),
                ('int_ph', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 't_photo',
                'verbose_name': 'Photo',
            },
        ),
        migrations.CreateModel(
            name='TPrestation',
            fields=[
                ('id_prest', models.AutoField(primary_key=True, serialize=False)),
                ('chem_pj_prest', models.CharField(blank=True, max_length=255, null=True)),
                ('comm_prest', models.CharField(blank=True, max_length=255, null=True)),
                ('dt_fin_prest', models.DateField(blank=True, null=True)),
                ('dt_notif_prest', models.DateField(blank=True, null=True)),
                ('int_prest', models.CharField(max_length=255)),
                ('mont_ht_tot_prest', models.FloatField()),
                ('mont_ttc_tot_prest', models.FloatField()),
            ],
            options={
                'db_table': 't_prestation',
            },
        ),
        migrations.CreateModel(
            name='TPrestationsDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mont_ht_prest', models.FloatField()),
                ('mont_ttc_prest', models.FloatField()),
                ('seq_ac', models.IntegerField(default=1)),
                ('seq_solde', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 't_prestations_dossier',
            },
        ),
        migrations.CreateModel(
            name='TProgramme',
            fields=[
                ('id_progr', models.AutoField(primary_key=True, serialize=False)),
                ('dim_progr', models.CharField(max_length=255, unique=True, verbose_name='Diminutif')),
                ('int_progr', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('seq_progr', models.IntegerField(default=1, verbose_name='Séquentiel')),
            ],
            options={
                'ordering': ['int_progr'],
                'db_table': 't_programme',
                'verbose_name': 'Programme',
            },
        ),
        migrations.CreateModel(
            name='TRegroupementsMoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': "Regroupements de maîtres d'ouvrages",
                'db_table': 't_regroupements_moa',
                'verbose_name': "Regroupement de maîtres d'ouvrages",
            },
        ),
        migrations.CreateModel(
            name='TRiviere',
            fields=[
                ('id_riv', models.AutoField(primary_key=True, serialize=False)),
                ('n_riv', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'ordering': ['n_riv'],
                'db_table': 't_riviere',
                'verbose_name': 'Rivière',
            },
        ),
        migrations.CreateModel(
            name='TRivieresDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_riv', models.ForeignKey(db_column='id_riv', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TRiviere')),
            ],
            options={
                'db_table': 't_rivieres_dossier',
            },
        ),
        migrations.CreateModel(
            name='TSage',
            fields=[
                ('id_sage', models.AutoField(primary_key=True, serialize=False)),
                ('n_sage', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'ordering': ['n_sage'],
                'verbose_name_plural': 'SAGE',
                'db_table': 't_sage',
                'verbose_name': 'SAGE',
            },
        ),
        migrations.CreateModel(
            name='TSousAxe',
            fields=[
                ('id_ss_axe', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ech_ss_axe', models.IntegerField(blank=True, null=True, verbose_name='Échéancier')),
                ('int_ss_axe', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('mont_ht_ss_axe', models.FloatField(blank=True, null=True, verbose_name='Montant HT')),
                ('mont_ttc_ss_axe', models.FloatField(blank=True, null=True, verbose_name='Montant TTC')),
                ('num_ss_axe', models.IntegerField(verbose_name='Numéro')),
                ('id_axe', models.ForeignKey(db_column='id_axe', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAxe', verbose_name='Axe')),
            ],
            options={
                'ordering': ['id_axe__id_progr__int_progr', 'id_axe__num_axe', 'num_ss_axe'],
                'db_table': 't_sous_axe',
                'verbose_name': 'Sous-axe',
            },
        ),
        migrations.CreateModel(
            name='TTechnicien',
            fields=[
                ('id_techn', models.AutoField(primary_key=True, serialize=False)),
                ('en_act', models.BooleanField(default=True, verbose_name='En activité')),
                ('n_techn', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('pren_techn', models.CharField(max_length=255, verbose_name='Prénom')),
            ],
            options={
                'ordering': ['n_techn', 'pren_techn'],
                'db_table': 't_technicien',
                'verbose_name': 'Technicien',
            },
        ),
        migrations.CreateModel(
            name='TTypeAvancementArrete',
            fields=[
                ('id_type_av_arr', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_av_arr', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('ordre_type_av_arr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordre_type_av_arr'],
                'verbose_name_plural': "Avancements d'un arrêté",
                'db_table': 't_type_avancement_arrete',
                'verbose_name': "Avancement d'un arrêté",
            },
        ),
        migrations.CreateModel(
            name='TTypeDeclaration',
            fields=[
                ('id_type_decl', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_decl', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('ordre_type_decl', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ordre_type_decl'],
                'verbose_name_plural': 'Types de déclarations',
                'db_table': 't_type_declaration',
                'verbose_name': 'Type de déclaration',
            },
        ),
        migrations.CreateModel(
            name='TTypeDossier',
            fields=[
                ('id_type_doss', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_doss', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_type_doss'],
                'verbose_name_plural': 'Types de dossiers',
                'db_table': 't_type_dossier',
                'verbose_name': 'Type de dossier',
            },
        ),
        migrations.CreateModel(
            name='TTypeGeom',
            fields=[
                ('id_type_geom', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_geom', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['int_type_geom'],
                'db_table': 't_type_geom',
            },
        ),
        migrations.CreateModel(
            name='TTypeProgramme',
            fields=[
                ('id_type_progr', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_progr', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_type_progr'],
                'verbose_name_plural': 'Types de programmes',
                'db_table': 't_type_programme',
                'verbose_name': 'Type de programme',
            },
        ),
        migrations.CreateModel(
            name='TTypesGeomTypeDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type_doss', models.ForeignKey(db_column='id_type_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDossier')),
                ('id_type_geom', models.ForeignKey(db_column='id_type_geom', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeGeom', verbose_name='Type de géométrie')),
            ],
            options={
                'db_table': 't_types_geom_type_dossier',
                'verbose_name': 'Types de géométries par type de dossier',
            },
        ),
        migrations.CreateModel(
            name='TTypesProgrammesTypeDossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type_doss', models.ForeignKey(db_column='id_type_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDossier')),
                ('id_type_progr', models.ForeignKey(db_column='id_type_progr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeProgramme', verbose_name='Type de programme')),
            ],
            options={
                'verbose_name_plural': 'Types de programmes par type de dossier',
                'db_table': 't_types_programmes_type_dossier',
                'verbose_name': 'Type de programme par type de dossier',
            },
        ),
        migrations.CreateModel(
            name='TTypeVersement',
            fields=[
                ('id_type_vers', models.AutoField(primary_key=True, serialize=False)),
                ('int_type_vers', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_type_vers'],
                'verbose_name_plural': 'Types de versements',
                'db_table': 't_type_versement',
                'verbose_name': 'Type de versement',
            },
        ),
        migrations.CreateModel(
            name='TUnite',
            fields=[
                ('id_unit', models.AutoField(primary_key=True, serialize=False)),
                ('int_unit', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'ordering': ['int_unit'],
                'db_table': 't_unite',
                'verbose_name': 'Unité',
            },
        ),
        migrations.CreateModel(
            name='TUtilisateur',
            fields=[
                ('id_util', models.OneToOneField(db_column='id_util', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('port_util', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone portable')),
                ('tel_util', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone')),
            ],
            options={
                'ordering': ['username'],
                'db_table': 't_utilisateur',
                'verbose_name': 'Utilisateur',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TFinanceur',
            fields=[
                ('id_org_fin', models.OneToOneField(db_column='id_org_fin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.TOrganisme')),
            ],
            options={
                'db_table': 't_financeur',
                'verbose_name': 'Financeur',
            },
            bases=('app.torganisme',),
        ),
        migrations.CreateModel(
            name='TMoa',
            fields=[
                ('id_org_moa', models.OneToOneField(db_column='id_org_moa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.TOrganisme')),
                ('dim_org_moa', models.CharField(max_length=255, unique=True, verbose_name='Diminutif')),
                ('en_act', models.BooleanField(default=True, verbose_name='En activité')),
            ],
            options={
                'verbose_name_plural': "Maîtres d'ouvrages",
                'db_table': 't_moa',
                'verbose_name': "Maître d'ouvrage",
            },
            bases=('app.torganisme',),
        ),
        migrations.CreateModel(
            name='TPgre',
            fields=[
                ('id_pgre', models.OneToOneField(db_column='id_pgre', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.TDossier')),
                ('quant_objs_pgre', models.FloatField(blank=True, null=True)),
                ('quant_real_pgre', models.FloatField(blank=True, null=True)),
                ('id_inst_conc', models.ForeignKey(blank=True, db_column='id_inst_conc', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TInstanceConcertation')),
                ('id_unit', models.ForeignKey(blank=True, db_column='id_unit', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TUnite')),
            ],
            options={
                'verbose_name_plural': 'Dossiers PGRE',
                'db_table': 't_pgre',
                'verbose_name': 'Dossier PGRE',
            },
            bases=('app.tdossier',),
        ),
        migrations.CreateModel(
            name='TPrestataire',
            fields=[
                ('id_org_prest', models.OneToOneField(db_column='id_org_prest', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.TOrganisme')),
                ('siret_org_prest', models.CharField(max_length=14, unique=True, verbose_name='Numéro SIRET')),
                ('num_dep', models.ForeignKey(db_column='num_dep', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDepartement', verbose_name='Département')),
            ],
            options={
                'db_table': 't_prestataire',
                'verbose_name': 'Prestataire',
            },
            bases=('app.torganisme',),
        ),
        migrations.AddField(
            model_name='tutilisateur',
            name='id_org',
            field=models.ForeignKey(db_column='id_org', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TOrganisme', verbose_name='Organisme'),
        ),
        migrations.AddField(
            model_name='ttypedossier',
            name='type_geom',
            field=models.ManyToManyField(through='app.TTypesGeomTypeDossier', to='app.TTypeGeom'),
        ),
        migrations.AddField(
            model_name='ttypedossier',
            name='type_progr',
            field=models.ManyToManyField(through='app.TTypesProgrammesTypeDossier', to='app.TTypeProgramme'),
        ),
        migrations.AddField(
            model_name='tprogramme',
            name='id_type_progr',
            field=models.ForeignKey(db_column='id_type_progr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeProgramme', verbose_name='Type de programme'),
        ),
        migrations.AddField(
            model_name='tprestationsdossier',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tprestationsdossier',
            name='id_prest',
            field=models.ForeignKey(db_column='id_prest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPrestation'),
        ),
        migrations.AddField(
            model_name='tprestation',
            name='doss',
            field=models.ManyToManyField(through='app.TPrestationsDossier', to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tprestation',
            name='id_nat_prest',
            field=models.ForeignKey(db_column='id_nat_prest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNaturePrestation'),
        ),
        migrations.AddField(
            model_name='tphoto',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tphoto',
            name='id_ppv_ph',
            field=models.ForeignKey(db_column='id_ppv_ph', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPeriodePriseVuePhoto'),
        ),
        migrations.AddField(
            model_name='torganisme',
            name='num_comm',
            field=models.ForeignKey(blank=True, db_column='num_comm', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TCommune', verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='tfinancement',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tfinancement',
            name='id_paiem_prem_ac',
            field=models.ForeignKey(blank=True, db_column='id_paiem_prem_ac', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPaiementPremierAcompte'),
        ),
        migrations.AddField(
            model_name='tfacture',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tfacture',
            name='id_prest',
            field=models.ForeignKey(db_column='id_prest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPrestation'),
        ),
        migrations.AddField(
            model_name='tdroit',
            name='id_type_progr',
            field=models.ForeignKey(db_column='id_type_progr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeProgramme'),
        ),
        migrations.AddField(
            model_name='tdroit',
            name='id_util',
            field=models.ForeignKey(db_column='id_util', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TUtilisateur'),
        ),
        migrations.AddField(
            model_name='tdossiergeom',
            name='id_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_av',
            field=models.ForeignKey(db_column='id_av', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAvancement'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_av_cp',
            field=models.ForeignKey(db_column='id_av_cp', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAvisCp'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_doss_ass',
            field=models.ForeignKey(blank=True, db_column='id_doss_ass', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_fam',
            field=models.ForeignKey(db_column='id_fam', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TFamille'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_nat_doss',
            field=models.ForeignKey(db_column='id_nat_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_progr',
            field=models.ForeignKey(db_column='id_progr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TProgramme'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_sage',
            field=models.ForeignKey(blank=True, db_column='id_sage', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TSage'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_techn',
            field=models.ForeignKey(db_column='id_techn', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTechnicien'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_type_doss',
            field=models.ForeignKey(db_column='id_type_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDossier'),
        ),
        migrations.AddField(
            model_name='tdemandeversement',
            name='fact',
            field=models.ManyToManyField(through='app.TFacturesDemandeVersement', to='app.TFacture'),
        ),
        migrations.AddField(
            model_name='tdemandeversement',
            name='id_fin',
            field=models.ForeignKey(db_column='id_fin', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TFinancement'),
        ),
        migrations.AddField(
            model_name='tdemandeversement',
            name='id_type_vers',
            field=models.ForeignKey(db_column='id_type_vers', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeVersement'),
        ),
        migrations.AddField(
            model_name='tcommunescp',
            name='cp_comm',
            field=models.ForeignKey(db_column='cp_comm', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TCp'),
        ),
        migrations.AddField(
            model_name='tcommunescp',
            name='num_comm',
            field=models.ForeignKey(db_column='num_comm', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TCommune'),
        ),
        migrations.AddField(
            model_name='taxe',
            name='id_progr',
            field=models.ForeignKey(db_column='id_progr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TProgramme', verbose_name='Programme'),
        ),
        migrations.AddField(
            model_name='tavenant',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tavenant',
            name='id_prest',
            field=models.ForeignKey(db_column='id_prest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPrestation'),
        ),
        migrations.AddField(
            model_name='tarretesdossier',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tarretesdossier',
            name='id_type_av_arr',
            field=models.ForeignKey(db_column='id_type_av_arr', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeAvancementArrete'),
        ),
        migrations.AddField(
            model_name='tarretesdossier',
            name='id_type_decl',
            field=models.ForeignKey(db_column='id_type_decl', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDeclaration'),
        ),
        migrations.AddField(
            model_name='taction',
            name='id_ss_axe',
            field=models.ForeignKey(db_column='id_ss_axe', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TSousAxe', verbose_name='Sous-axe'),
        ),
        migrations.AlterUniqueTogether(
            name='tsousaxe',
            unique_together=set([('num_ss_axe', 'id_axe')]),
        ),
        migrations.AddField(
            model_name='trivieresdossier',
            name='id_pgre',
            field=models.ForeignKey(db_column='id_pgre', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPgre'),
        ),
        migrations.AddField(
            model_name='tregroupementsmoa',
            name='id_org_moa_anc',
            field=models.ForeignKey(db_column='id_org_moa_anc', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_org_moa_anc', to='app.TMoa', verbose_name="Maître d'ouvrage ancien"),
        ),
        migrations.AddField(
            model_name='tregroupementsmoa',
            name='id_org_moa_fil',
            field=models.ForeignKey(db_column='id_org_moa_fil', on_delete=django.db.models.deletion.DO_NOTHING, related_name='id_org_moa_fil', to='app.TMoa', verbose_name="Maître d'ouvrage par filiation"),
        ),
        migrations.AddField(
            model_name='tprestation',
            name='id_org_prest',
            field=models.ForeignKey(db_column='id_org_prest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPrestataire'),
        ),
        migrations.AddField(
            model_name='tpgre',
            name='riv',
            field=models.ManyToManyField(through='app.TRivieresDossier', to='app.TRiviere'),
        ),
        migrations.AddField(
            model_name='tmoa',
            name='moa',
            field=models.ManyToManyField(related_name='_tmoa_moa_+', through='app.TRegroupementsMoa', to='app.TMoa'),
        ),
        migrations.AddField(
            model_name='tfinancement',
            name='id_org_fin',
            field=models.ForeignKey(blank=True, db_column='id_org_fin', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TFinanceur'),
        ),
        migrations.AddField(
            model_name='tdroit',
            name='id_org_moa',
            field=models.ForeignKey(db_column='id_org_moa', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TMoa'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='id_org_moa',
            field=models.ForeignKey(db_column='id_org_moa', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TMoa'),
        ),
        migrations.AlterUniqueTogether(
            name='taxe',
            unique_together=set([('num_axe', 'id_progr')]),
        ),
        migrations.AlterUniqueTogether(
            name='tarretesdossier',
            unique_together=set([('id_doss', 'id_type_decl')]),
        ),
        migrations.AlterUniqueTogether(
            name='taction',
            unique_together=set([('num_act', 'id_ss_axe')]),
        ),
        migrations.AlterUniqueTogether(
            name='tdroit',
            unique_together=set([('id_org_moa', 'id_type_progr', 'id_util')]),
        ),
    ]
