# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-26 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfacture',
            options={'ordering': ['id_prest'], 'verbose_name': 'T_FACTURE', 'verbose_name_plural': 'T_FACTURE'},
        ),
        migrations.AlterModelOptions(
            name='tprestation',
            options={'ordering': ['id_org_prest', 'dt_notif_prest', 'int_prest'], 'verbose_name': 'T_PRESTATION', 'verbose_name_plural': 'T_PRESTATION'},
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.date(2017, 1, 26)),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='dim_org_moa',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Diminutif'),
        ),
    ]
