# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-01 07:13
from __future__ import unicode_literals

import app.models
import app.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170126_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tprestation',
            name='mont_prest',
        ),
        migrations.AddField(
            model_name='tavenant',
            name='chem_pj_aven',
            field=models.FileField(blank=True, null=True, upload_to=app.models.TAvenant.set_chem_pj_aven_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer le fichier scanné de l\'avenant <span class="field-complement">(fichier PDF)</span>'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 2, 1, 7, 13, 21, 532167, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TProgramme'),
        ),
    ]
