# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 10:24
from __future__ import unicode_literals

import app.models
import app.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170201_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='chem_pj_doss',
            field=models.FileField(blank=True, null=True, upload_to=app.models.TDossier.set_chem_pj_doss_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='\n        Insérer le fichier scanné du mémoire technique <span class="field-complement">(fichier PDF)</span>\n        '),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 2, 3, 10, 24, 0, 55205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='dim_org_moa',
            field=models.CharField(max_length=255, unique=True, verbose_name='Diminutif'),
        ),
    ]
