# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-17 08:03
from __future__ import unicode_literals

import app.models
import app.validators
import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170203_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAtelierPgre',
            fields=[
                ('id_atel_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('int_atel_pgre', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name_plural': 'T_ATELIER_PGRE',
                'ordering': ['int_atel_pgre'],
                'db_table': 't_atelier_pgre',
                'verbose_name': 'T_ATELIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TAteliersPgreDossierPgre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atel_pgre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAtelierPgre')),
            ],
            options={
                'verbose_name_plural': 'T_ATELIERS_PGRE_DOSSIER_PGRE',
                'db_table': 't_ateliers_pgre_dossier_pgre',
                'verbose_name': 'T_ATELIERS_PGRE_DOSSIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TAvancementPgre',
            fields=[
                ('id_av_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('int_av_pgre', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('ordre_av_pgre', models.IntegerField(verbose_name='Ordre dans la liste déroulante')),
            ],
            options={
                'verbose_name_plural': 'T_AVANCEMENT_PGRE',
                'ordering': ['ordre_av_pgre'],
                'db_table': 't_avancement_pgre',
                'verbose_name': 'T_AVANCEMENT_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TControleDossierPgre',
            fields=[
                ('id_contr_doss_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('dt_contr_doss_pgre', models.DateField()),
                ('obj_real_contr_doss_pgre', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'T_CONTROLE_DOSSIER_PGRE',
                'ordering': ['-dt_contr_doss_pgre'],
                'db_table': 't_controle_dossier_pgre',
                'verbose_name': 'T_CONTROLE_DOSSIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TDossierPgre',
            fields=[
                ('id_doss_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('ann_prev_deb_doss_pgre', models.IntegerField(verbose_name="Année prévisionnelle du début de l'action PGRE")),
                ('chem_pj_doss_pgre', models.FileField(blank=True, null=True, upload_to=app.models.TDossierPgre.set_chem_pj_doss_pgre_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer la fiche action <span class="field-complement">(fichier PDF)</span>')),
                ('comm_doss_pgre', models.TextField(blank=True, null=True, validators=[app.validators.val_cdc], verbose_name='Commentaire')),
                ('dt_deb_doss_pgre', models.DateField(verbose_name="Date de début de l'action PGRE")),
                ('dt_fin_doss_pgre', models.DateField(verbose_name="Date de fin de l'action PGRE")),
                ('int_doss_pgre', models.CharField(max_length=255, validators=[app.validators.val_cdc], verbose_name="Intitulé de l'action PGRE")),
                ('num_doss_pgre', models.CharField(max_length=255, unique=True, validators=[app.validators.val_cdc], verbose_name="Numéro de l'action PGRE")),
                ('obj_econ_ress_doss_pgre', models.FloatField(verbose_name="Objectifs d'économie de la ressource en eau (en m<sup>3</sup>)")),
                ('atel_pgre', models.ManyToManyField(through='app.TAteliersPgreDossierPgre', to='app.TAtelierPgre')),
                ('id_av_pgre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAvancementPgre', verbose_name="État d'avancement")),
            ],
            options={
                'verbose_name_plural': 'T_DOSSIER_PGRE',
                'ordering': ['num_doss_pgre'],
                'db_table': 't_dossier_pgre',
                'verbose_name': 'T_DOSSIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TDossierPgreGeom',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom_lin', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=2154)),
                ('geom_pct', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=2154)),
                ('geom_pol', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=2154)),
                ('id_doss_pgre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre')),
            ],
            options={
                'verbose_name_plural': 'T_DOSSIER_PGRE_GEOM',
                'db_table': 't_dossier_pgre_geom',
                'verbose_name': 'T_DOSSIER_PGRE_GEOM',
            },
        ),
        migrations.CreateModel(
            name='TInstanceConcertationPgre',
            fields=[
                ('id_ic_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('int_ic_pgre', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name_plural': 'T_INSTANCE_CONCERTATION_PGRE',
                'ordering': ['int_ic_pgre'],
                'db_table': 't_instance_concertation_pgre',
                'verbose_name': 'T_INSTANCE_CONCERTATION_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TInstancesConcertationPgreAtelierPgre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atel_pgre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAtelierPgre')),
                ('id_ic_pgre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TInstanceConcertationPgre')),
            ],
            options={
                'verbose_name_plural': 'T_INSTANCES_CONCERTATION_PGRE_ATELIER_PGRE',
                'db_table': 't_instances_concertation_pgre_atelier_pgre',
                'verbose_name': 'T_INSTANCES_CONCERTATION_PGRE_ATELIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TMoaDossierPgre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doss_pgre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossierPgre')),
            ],
            options={
                'verbose_name_plural': 'T_MOA_DOSSIER_PGRE',
                'db_table': 't_moa_dossier_pgre',
                'verbose_name': 'T_MOA_DOSSIER_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TPhotoPgre',
            fields=[
                ('id_ph_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('chem_ph_pgre', models.FileField(upload_to=app.models.TPhotoPgre.set_chem_ph_pgre_upload_to, validators=[app.validators.val_fich_img])),
                ('descr_ph_pgre', models.CharField(blank=True, max_length=255, null=True, validators=[app.validators.val_cdc])),
                ('dt_pv_ph_pgre', models.DateField()),
                ('int_ph_pgre', models.CharField(max_length=255, validators=[app.validators.val_cdc])),
            ],
            options={
                'verbose_name_plural': 'T_PHOTO_PGRE',
                'db_table': 't_photo_pgre',
                'verbose_name': 'T_PHOTO_PGRE',
            },
        ),
        migrations.CreateModel(
            name='TPrioritePgre',
            fields=[
                ('id_pr_pgre', models.AutoField(primary_key=True, serialize=False)),
                ('int_pr_pgre', models.CharField(max_length=255, verbose_name='Intitulé')),
            ],
            options={
                'verbose_name_plural': 'T_PRIORITE_PGRE',
                'ordering': ['int_pr_pgre'],
                'db_table': 't_priorite_pgre',
                'verbose_name': 'T_PRIORITE_PGRE',
            },
        ),
        migrations.RenameField(
            model_name='tprogramme',
            old_name='en_act_progr',
            new_name='en_act',
        ),
        migrations.RenameField(
            model_name='ttechnicien',
            old_name='en_act_techn',
            new_name='en_act',
        ),
        migrations.RemoveField(
            model_name='tmoa',
            name='en_act_org_moa',
        ),
        migrations.AddField(
            model_name='tdemandeversement',
            name='num_bord_ddv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro de bordereau'),
        ),
        migrations.AddField(
            model_name='tdemandeversement',
            name='num_titre_rec_ddv',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro de titre de recette'),
        ),
        migrations.AddField(
            model_name='tmoa',
            name='en_act_doss',
            field=models.BooleanField(default=True, verbose_name='En activité (gestion des dossiers)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmoa',
            name='en_act_doss_pgre',
            field=models.BooleanField(default=False, verbose_name='En activité (gestion des actions PGRE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmoa',
            name='peu_doss',
            field=models.BooleanField(default=True, verbose_name='Utilisé (gestion des dossiers)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tmoa',
            name='peu_doss_pgre',
            field=models.BooleanField(default=False, verbose_name='Utilisé (gestion des actions PGRE)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tnaturedossier',
            name='peu_doss',
            field=models.BooleanField(default=True, verbose_name='Autorisée (gestion des dossiers)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tnaturedossier',
            name='peu_doss_pgre',
            field=models.BooleanField(default=True, verbose_name='Autorisée (gestion des actions PGRE)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 2, 17, 8, 2, 0, 193721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier'),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='dim_org_moa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Diminutif'),
        ),
        migrations.AddField(
            model_name='tphotopgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tphotopgre',
            name='id_ppv_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPeriodePriseVuePhoto'),
        ),
        migrations.AddField(
            model_name='tmoadossierpgre',
            name='id_org_moa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TMoa'),
        ),
        migrations.AddField(
            model_name='tdossierpgre',
            name='id_doss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossier'),
        ),
        migrations.AddField(
            model_name='tdossierpgre',
            name='id_ic_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TInstanceConcertationPgre', verbose_name='Instance de concertation'),
        ),
        migrations.AddField(
            model_name='tdossierpgre',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier', verbose_name="Nature de l'action PGRE"),
        ),
        migrations.AddField(
            model_name='tdossierpgre',
            name='id_pr_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPrioritePgre', verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='tdossierpgre',
            name='moa',
            field=models.ManyToManyField(through='app.TMoaDossierPgre', to='app.TMoa'),
        ),
        migrations.AddField(
            model_name='tcontroledossierpgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossierPgre'),
        ),
        migrations.AddField(
            model_name='tatelierspgredossierpgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossierPgre'),
        ),
        migrations.AddField(
            model_name='tatelierpgre',
            name='ic_pgre',
            field=models.ManyToManyField(through='app.TInstancesConcertationPgreAtelierPgre', to='app.TInstanceConcertationPgre'),
        ),
    ]
