# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 12:41
from __future__ import unicode_literals

import app.models
import app.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170221_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tatelierspgredossierpgre',
            options={'ordering': ['id_atel_pgre'], 'verbose_name': 'T_ATELIERS_PGRE_DOSSIER_PGRE', 'verbose_name_plural': 'T_ATELIERS_PGRE_DOSSIER_PGRE'},
        ),
        migrations.AlterModelOptions(
            name='tcontroledossierpgre',
            options={'ordering': ['dt_contr_doss_pgre'], 'verbose_name': 'T_CONTROLE_DOSSIER_PGRE', 'verbose_name_plural': 'T_CONTROLE_DOSSIER_PGRE'},
        ),
        migrations.AlterModelOptions(
            name='tmoadossierpgre',
            options={'ordering': ['id_org_moa'], 'verbose_name': 'T_MOA_DOSSIER_PGRE', 'verbose_name_plural': 'T_MOA_DOSSIER_PGRE'},
        ),
        migrations.AlterField(
            model_name='tcontroledossierpgre',
            name='dt_contr_doss_pgre',
            field=models.DateField(verbose_name='Date du contrôle'),
        ),
        migrations.AlterField(
            model_name='tcontroledossierpgre',
            name='obj_real_contr_doss_pgre',
            field=models.FloatField(verbose_name="Objectif réalisé en terme d'économie de la ressource en eau (en m<sup>3</sup>)"),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 2, 27, 12, 41, 21, 975674, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='chem_ph_pgre',
            field=models.FileField(upload_to=app.models.TPhotoPgre.set_chem_ph_pgre_upload_to, validators=[app.validators.val_fich_img], verbose_name='Insérer une photo <span class="field-complement">(taille limitée à 3 Mo)</span>'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='descr_ph_pgre',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[app.validators.val_cdc], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='dt_pv_ph_pgre',
            field=models.DateField(verbose_name='Date de prise de vue'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TDossierPgre'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='id_ppv_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TPeriodePriseVuePhoto', verbose_name='Période de prise de vue'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='int_ph_pgre',
            field=models.CharField(max_length=255, validators=[app.validators.val_cdc], verbose_name='Intitulé de la photo'),
        ),
    ]
