# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 08:15
from __future__ import unicode_literals

import app.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170310_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavenant',
            options={'ordering': ['num_aven'], 'verbose_name': 'T_AVENANT', 'verbose_name_plural': 'T_AVENANT'},
        ),
        migrations.AlterModelOptions(
            name='tdemandeversement',
            options={'ordering': ['-dt_ddv'], 'verbose_name': 'T_DEMANDE_VERSEMENT', 'verbose_name_plural': 'T_DEMANDE_VERSEMENT'},
        ),
        migrations.AlterModelOptions(
            name='tfacture',
            options={'ordering': ['-dt_mand_moa_fact', 'id_prest'], 'verbose_name': 'T_FACTURE', 'verbose_name_plural': 'T_FACTURE'},
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='dt_lim_encl_trav_arr',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite d\'enclenchement des travaux <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='dt_sign_arr',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature de l\'arrêté <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tavenant',
            name='dt_aven',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de l\'avenant <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tavenant',
            name='mont_aven',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_nul], verbose_name="Montant [ht_ou_ttc] de l'avenant"),
        ),
        migrations.AlterField(
            model_name='tcontroledossierpgre',
            name='dt_contr_doss_pgre',
            field=models.DateField(verbose_name='Date du contrôle <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='dt_ddv',
            field=models.DateField(verbose_name='Date de la demande de versement <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='dt_vers_ddv',
            field=models.DateField(blank=True, null=True, verbose_name='Date de versement <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ht_ddv',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_pos], verbose_name='Montant HT de la demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ht_verse_ddv',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_nul], verbose_name='Montant HT versé'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ttc_ddv',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_pos], verbose_name='Montant TTC de la demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ttc_verse_ddv',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_nul], verbose_name='Montant TTC versé'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_av_cp_doss',
            field=models.DateField(blank=True, null=True, verbose_name='Date de l\'avis du comité de programmation <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_delib_moa_doss',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délibération au maître d\'ouvrage <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 4, 12, 8, 15, 0, 221449, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_doss',
            field=models.FloatField(validators=[app.validators.val_mont_pos], verbose_name='Montant du dossier présenté au CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_suppl_doss',
            field=models.FloatField(default=0, validators=[app.validators.val_mont_nul], verbose_name='Dépassement du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='dt_deb_doss_pgre',
            field=models.DateField(verbose_name='Date de début de l\'action PGRE <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='dt_fin_doss_pgre',
            field=models.DateField(verbose_name='Date de fin de l\'action PGRE <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfacture',
            name='dt_mand_moa_fact',
            field=models.DateField(verbose_name='Date de mandatement par le maître d\'ouvrage <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfacture',
            name='dt_rec_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception de la facture <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfacture',
            name='mont_ht_fact',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_pos], verbose_name='Montant HT de la facture'),
        ),
        migrations.AlterField(
            model_name='tfacture',
            name='mont_ttc_fact',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_pos], verbose_name='Montant TTC de la facture'),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='dt_deb_elig_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début d\'éligibilité <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='dt_lim_deb_oper_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du début de l\'opération <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='dt_lim_prem_ac_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date limite du premier acompte <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='duree_pror_fin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée de la prorogation (en mois)'),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='duree_valid_fin',
            field=models.IntegerField(blank=True, null=True, verbose_name="Durée de validité de l'aide (en mois)"),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='mont_elig_fin',
            field=models.FloatField(blank=True, null=True, validators=[app.validators.val_mont_pos], verbose_name="Montant [ht_ou_ttc] de l'assiette éligible de la subvention"),
        ),
        migrations.AlterField(
            model_name='tfinancement',
            name='mont_part_fin',
            field=models.FloatField(validators=[app.validators.val_mont_pos], verbose_name='Montant [ht_ou_ttc] total de la participation'),
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='courr_org',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse électronique'),
        ),
        migrations.AlterField(
            model_name='tphoto',
            name='dt_pv_ph',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prise de vue <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='dt_pv_ph_pgre',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prise de vue <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='dt_fin_prest',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de la prestation <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='dt_notif_prest',
            field=models.DateField(verbose_name='Date de notification de la prestation <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
    ]
