# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 12:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170412_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 4, 12, 12, 25, 46, 552124, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tfacture',
            name='dt_mand_moa_fact',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mandatement par le maître d\'ouvrage <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='dt_notif_prest',
            field=models.DateField(blank=True, null=True, verbose_name='Date de notification de la prestation <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
    ]
