# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170412_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tprestationsdossier',
            name='seq_ac_prest_doss',
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 4, 14, 9, 12, 1, 280806, tzinfo=utc)),
        ),
    ]
