# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170414_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 4, 21, 12, 46, 17, 589708, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='dt_deb_doss_pgre',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début de l\'action PGRE <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='dt_fin_doss_pgre',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin de l\'action PGRE <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
    ]
