# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-06 09:43
from __future__ import unicode_literals

import app.validators
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170421_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavancement',
            options={'ordering': ['ordre_av', 'int_av'], 'verbose_name': 'T_AVANCEMENT', 'verbose_name_plural': 'T_AVANCEMENT'},
        ),
        migrations.AddField(
            model_name='tavancement',
            name='id_av_pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TAvancement', verbose_name="État d'avancement père"),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='annee_prev_doss',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année prévisionnelle du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 6, 6, 9, 43, 11, 917970, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_doss',
            field=models.FloatField(validators=[app.validators.val_mont_nul], verbose_name='Montant du dossier présenté au CD GEMAPI'),
        ),
    ]
