# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-27 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170620_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 9, 27, 9, 43, 29, 958476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier', verbose_name='Nature du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TProgramme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_techn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTechnicien', verbose_name='Agent responsable'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_type_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDossier', verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TNatureDossier', verbose_name="Nature de l'action PGRE"),
        ),
    ]
