# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-30 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170927_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2017, 10, 30, 10, 5, 3, 594822, tzinfo=utc)),
        ),
    ]
