# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-17 10:25
from __future__ import unicode_literals

import app.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171030_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdossierpgre',
            name='mont_doss_pgre',
            field=models.FloatField(default=0.0, validators=[app.validators.val_mont_nul], verbose_name='Montant dossier PGRE'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 10, 25, 56, 410408, tzinfo=utc)),
        ),
    ]
