# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-17 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180417_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAvancementPgreTraces',
            fields=[
                ('id_trace', models.AutoField(primary_key=True, serialize=False)),
                ('date_modif_av', models.DateTimeField(auto_now_add=True, verbose_name="Horodatage du changement d'état d'avancement")),
                ('id_av_pgre', models.ForeignKey(db_column='id_av_pgre', on_delete=django.db.models.deletion.CASCADE, to='app.TAvancementPgre')),
                ('id_doss_pgre', models.ForeignKey(db_column='id_doss_pgre_integer', on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre')),
            ],
            options={
                'db_table': 't_avancement_pgre_traces',
                'ordering': ('id_trace',),
            },
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 13, 35, 20, 39965, tzinfo=utc)),
        ),
    ]
