# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-17 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180417_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDossierSsAction',
            fields=[
                ('id_ss_act', models.AutoField(primary_key=True, serialize=False)),
                ('lib_ss_act', models.CharField(max_length=255, verbose_name='Libellé')),
                ('desc_ss_act', models.TextField(blank=True, null=True, verbose_name='Descriptif')),
                ('comm_ss_act', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('dt_prevision_ss_action_pgre', models.DateTimeField(verbose_name='Prévisionnel')),
                ('dt_deb_ss_action_pgre', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('dt_fin_ss_action_pgre', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('mont_ss_action_pgre', models.FloatField(verbose_name='Montant')),
                ('obj_econ_ress_ss_action_pgre', models.FloatField(verbose_name="Objectif d'économie de ressource")),
                ('id_av_pgre', models.ForeignKey(db_column='id_av_pgre', on_delete=django.db.models.deletion.CASCADE, to='app.TAvancementPgre')),
                ('moa', models.ManyToManyField(to='app.TMoa')),
                ('t_nature_dossier', models.ForeignKey(db_column='id_nat_doss', on_delete=django.db.models.deletion.CASCADE, to='app.TNatureDossier')),
            ],
            options={
                'db_table': 't_dossier_pgre_ss_action',
            },
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2018, 4, 17, 14, 45, 34, 404594, tzinfo=utc)),
        ),
    ]
