# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-19 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180419_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdossierpgre',
            name='ss_action_pgre',
            field=models.ManyToManyField(to='app.TDossierSsAction'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2018, 4, 19, 13, 5, 3, 990610, tzinfo=utc)),
        ),
    ]
