# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-26 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180419_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2018, 4, 26, 13, 54, 7, 181875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='dt_deb_ss_action_pgre',
            field=models.DateField(blank=True, null=True, verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='dt_fin_ss_action_pgre',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='dt_prevision_ss_action_pgre',
            field=models.DateField(verbose_name='Prévisionnel'),
        ),
    ]
