# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190121_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavancement',
            name='id_av_pere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TAvancement', verbose_name="État d'avancement père"),
        ),
        migrations.AlterField(
            model_name='tavancement',
            name='ordre_av',
            field=models.IntegerField(verbose_name='Ordre (liste déroulante)'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 13, 47, 53, 645756, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tnaturedossier',
            name='peu_doss',
            field=models.BooleanField(default=False, verbose_name='Est-elle autorisée (module Gestion des dossiers) ?'),
        ),
        migrations.AlterField(
            model_name='tnaturedossier',
            name='peu_doss_pgre',
            field=models.BooleanField(default=False, verbose_name='Est-elle autorisée (module PGRE) ?'),
        ),
        migrations.AlterField(
            model_name='ttechnicien',
            name='en_act',
            field=models.BooleanField(default=True, verbose_name='Est-il en activité ?'),
        ),
    ]
