# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190121_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxe',
            name='id_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TProgramme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='taxe',
            name='num_axe',
            field=models.CharField(max_length=255, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 14, 11, 38, 371096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tprogramme',
            name='dim_progr',
            field=models.CharField(help_text="Utilisé pour la création d'un numéro de dossier", max_length=255, unique=True, verbose_name='Diminutif'),
        ),
        migrations.AlterField(
            model_name='tprogramme',
            name='en_act',
            field=models.BooleanField(default=True, verbose_name='Est-il en activité ?'),
        ),
        migrations.AlterField(
            model_name='tprogramme',
            name='id_type_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeProgramme', verbose_name='Type de programme'),
        ),
        migrations.AlterField(
            model_name='tprogramme',
            name='seq_progr',
            field=models.PositiveIntegerField(default=1, help_text="Utilisé pour la création d'un numéro de dossier", verbose_name='Séquentiel'),
        ),
        migrations.AlterField(
            model_name='ttypesgeomtypedossier',
            name='id_type_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeDossier', verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='ttypesgeomtypedossier',
            name='id_type_geom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeGeom', verbose_name='Type de géométrie'),
        ),
        migrations.AlterField(
            model_name='ttypesprogrammestypedossier',
            name='id_type_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TTypeDossier', verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='ttypesprogrammestypedossier',
            name='id_type_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeProgramme', verbose_name='Type de programme'),
        ),
    ]
