# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190121_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taction',
            name='ech_act',
        ),
        migrations.RemoveField(
            model_name='taction',
            name='mont_ht_act',
        ),
        migrations.RemoveField(
            model_name='taction',
            name='mont_ttc_act',
        ),
        migrations.RemoveField(
            model_name='tsousaxe',
            name='ech_ss_axe',
        ),
        migrations.RemoveField(
            model_name='tsousaxe',
            name='mont_ht_ss_axe',
        ),
        migrations.RemoveField(
            model_name='tsousaxe',
            name='mont_ttc_ss_axe',
        ),
        migrations.AlterField(
            model_name='taction',
            name='id_ss_axe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TSousAxe', verbose_name='Sous-axe'),
        ),
        migrations.AlterField(
            model_name='taction',
            name='num_act',
            field=models.CharField(max_length=255, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 14, 45, 52, 624838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tsousaxe',
            name='id_axe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAxe', verbose_name='Axe'),
        ),
        migrations.AlterField(
            model_name='tsousaxe',
            name='num_ss_axe',
            field=models.CharField(max_length=255, verbose_name='Numéro'),
        ),
    ]
