# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 15:06
from __future__ import unicode_literals

import app.classes.MFPhoneNumberField
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20190121_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcommunescp',
            name='cp_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TCp'),
        ),
        migrations.AlterField(
            model_name='tcommunescp',
            name='num_comm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TCommune'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 15, 5, 21, 170622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='adr_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse (ligne 1)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='bp_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Boîte postale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='cedex_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cedex'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='comm_org',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='compl_adr_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse (ligne 2)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='cont_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Contact'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='courr_org',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Adresse électronique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='cp_org',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Code postal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='num_comm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TCommune', verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='port_org',
            field=app.classes.MFPhoneNumberField.Class(blank=True, default='', max_length=10, verbose_name='Numéro de téléphone portable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='site_web_org',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Site web'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torganisme',
            name='tel_org',
            field=app.classes.MFPhoneNumberField.Class(blank=True, default='', max_length=10, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
