# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 15:35
from __future__ import unicode_literals

import app.models.tables
import app.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190121_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 15, 34, 47, 322008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='dim_org_moa',
            field=models.CharField(blank=True, default='', help_text="Utilisé pour la création d'un numéro de dossier", max_length=255, verbose_name='Diminutif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='en_act_doss',
            field=models.BooleanField(default=True, verbose_name='Est-il en activité (module Gestion des dossiers) ?'),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='en_act_doss_pgre',
            field=models.BooleanField(default=True, verbose_name='Est-il en activité (module PGRE) ?'),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='logo_org_moa',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TMoa.set_logo_org_moa_upload_to, validators=[app.validators.val_fich_img], verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='peu_doss',
            field=models.BooleanField(default=True, verbose_name='Est-il autorisé (module Gestion des dossiers) ?'),
        ),
        migrations.AlterField(
            model_name='tmoa',
            name='peu_doss_pgre',
            field=models.BooleanField(default=True, verbose_name='Est-il autorisé (module PGRE) ?'),
        ),
    ]
