# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 15:41
from __future__ import unicode_literals

import app.classes.MFPhoneNumberField
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190121_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 15, 40, 55, 394569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tregroupementsmoa',
            name='id_org_moa_anc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_org_moa_anc', to='app.TMoa', verbose_name="Maître d'ouvrage (ancien)"),
        ),
        migrations.AlterField(
            model_name='tregroupementsmoa',
            name='id_org_moa_fil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_org_moa_fil', to='app.TMoa', verbose_name="Maître d'ouvrage (nouveau)"),
        ),
        migrations.AlterField(
            model_name='tutilisateur',
            name='id_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TOrganisme', verbose_name='Organisme'),
        ),
        migrations.AlterField(
            model_name='tutilisateur',
            name='port_util',
            field=app.classes.MFPhoneNumberField.Class(blank=True, default='', max_length=10, verbose_name='Numéro de téléphone portable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutilisateur',
            name='tel_util',
            field=app.classes.MFPhoneNumberField.Class(blank=True, default='', max_length=10, verbose_name='Numéro de téléphone'),
            preserve_default=False,
        ),
    ]
