# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20190121_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tdroit',
            options={'ordering': ['id'], 'verbose_name': 'T_DROIT', 'verbose_name_plural': 'T_DROIT'},
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 15, 50, 52, 595516, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tdroit',
            name='id_org_moa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TMoa', verbose_name="Maître d'ouvrage"),
        ),
        migrations.AlterField(
            model_name='tdroit',
            name='id_type_progr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TTypeProgramme', verbose_name='Type de programme'),
        ),
        migrations.AlterField(
            model_name='tdroit',
            name='id_util',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TUtilisateur', verbose_name='Utilisateur'),
        ),
    ]
