# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20190121_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(default=datetime.datetime(2019, 1, 21, 15, 53, 3, 993984, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ttypeavancementarrete',
            name='ordre_type_av_arr',
            field=models.PositiveIntegerField(default=9999, verbose_name='Ordre (liste déroulante)'),
        ),
    ]
