# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 17:24
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.models.tables
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20190121_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='annee_prev_doss',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année prévisionnelle du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='chem_pj_doss',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TDossier.set_chem_pj_doss_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='\n        Insérer le fichier scanné du mémoire technique <span class="field-complement">(fichier PDF)</span>\n        '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='comm_doss',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='comm_regl_doss',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_int_doss',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAvancement', verbose_name="État d'avancement"),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_av_cp',
            field=models.ForeignKey(default=app.models.tables.TDossier.set_id_av_cp_default, on_delete=django.db.models.deletion.CASCADE, to='app.TAvisCp', verbose_name='Avis du comité de programmation - CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_doss_ass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TDossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TNatureDossier', verbose_name='Nature du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_org_moa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TMoa'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_progr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TProgramme', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_sage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TSage', verbose_name='SAGE'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_techn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTechnicien', verbose_name='Agent responsable'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_type_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeDossier', verbose_name='Type de dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='lib_1_doss',
            field=models.CharField(max_length=255, verbose_name='Caractéristique'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='lib_2_doss',
            field=models.CharField(max_length=255, verbose_name='Territoire et lieu-dit'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_doss',
            field=app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Montant du dossier présenté au CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_suppl_doss',
            field=app.classes.MFEuroField.Class(decimal_places=2, default=0, max_digits=26, verbose_name='Dépassement du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='num_act',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='num_axe',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='num_ss_axe',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
