# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190121_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tperiodeprisevuephoto',
            name='ordre_ppv_ph',
            field=models.PositiveIntegerField(default=9999, verbose_name='Ordre (liste déroulante)'),
        ),
        migrations.AlterField(
            model_name='tphoto',
            name='descr_ph',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tphoto',
            name='id_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossier'),
        ),
        migrations.AlterField(
            model_name='tphoto',
            name='id_ppv_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TPeriodePriseVuePhoto', verbose_name='Période de prise de vue'),
        ),
        migrations.AlterField(
            model_name='tphoto',
            name='int_ph',
            field=models.CharField(max_length=255, verbose_name='Intitulé de la photo'),
        ),
    ]
