# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 17:48
from __future__ import unicode_literals

import app.models.tables
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20190121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarretesdossier',
            name='chem_pj_arr',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TArretesDossier.set_chem_pj_arr_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer le fichier scanné de l\'arrêté <span class="field-complement">(fichier PDF)</span>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='comm_arr',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='id_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossier'),
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='id_type_av_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeAvancementArrete', verbose_name='Avancement'),
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='id_type_decl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeDeclaration'),
        ),
        migrations.AlterField(
            model_name='tarretesdossier',
            name='num_arr',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Numéro de l'arrêté"),
            preserve_default=False,
        ),
    ]
