# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20190121_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprestataire',
            name='num_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TDepartement', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='tprestataire',
            name='siret_org_prest',
            field=models.CharField(max_length=14, unique=True, verbose_name='Numéro SIRET'),
        ),
    ]
