# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-21 17:58
from __future__ import unicode_literals

import app.models.tables
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20190121_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprestation',
            name='chem_pj_prest',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TPrestation.set_chem_pj_prest_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer le contrat de prestation <span class="field-complement">(fichier PDF)</span>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='comm_prest',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='id_nat_prest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TNaturePrestation', verbose_name='Nature de la prestation'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='id_org_prest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TPrestataire'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='int_prest',
            field=models.CharField(max_length=255, verbose_name='Intitulé de la prestation'),
        ),
        migrations.AlterField(
            model_name='tprestation',
            name='ref_prest',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Référence de la prestation'),
            preserve_default=False,
        ),
    ]
