# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 08:12
from __future__ import unicode_literals

import app.classes.MFEuroField
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20190121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprestationsdossier',
            name='id_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossier'),
        ),
        migrations.AlterField(
            model_name='tprestationsdossier',
            name='id_prest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TPrestation'),
        ),
        migrations.AlterField(
            model_name='tprestationsdossier',
            name='mont_prest_doss',
            field=app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='tprestationsdossier',
            name='seq_aven_prest_doss',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
