# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 08:28
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.models.tables
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20190122_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tavenant',
            name='chem_pj_aven',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TAvenant.set_chem_pj_aven_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer le fichier scanné de l\'avenant <span class="field-complement">(fichier PDF)</span>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tavenant',
            name='comm_aven',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tavenant',
            name='int_aven',
            field=models.CharField(max_length=255, verbose_name="Intitulé de l'avenant"),
        ),
        migrations.AlterField(
            model_name='tavenant',
            name='mont_aven',
            field=app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True, verbose_name="Montant [ht_ou_ttc] de l'avenant"),
        ),
    ]
