# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 09:15
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.models.tables
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20190122_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdemandeversement',
            name='chem_pj_ddv',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TDemandeVersement.set_chem_pj_ddv_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='\n        Insérer le courrier scanné de la demande de versement <span class="field-complement">(fichier PDF)</span>\n        '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='comm_ddv',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='id_fin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TFinancement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='id_type_vers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TTypeVersement', verbose_name='Type de demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='int_ddv',
            field=models.CharField(max_length=255, verbose_name='Intitulé de la demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ht_ddv',
            field=app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True, verbose_name='Montant HT de la demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ht_verse_ddv',
            field=app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True, verbose_name='Montant HT versé'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ttc_ddv',
            field=app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True, verbose_name='Montant TTC de la demande de versement'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='mont_ttc_verse_ddv',
            field=app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True, verbose_name='Montant TTC versé'),
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='num_bord_ddv',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Numéro de bordereau'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdemandeversement',
            name='num_titre_rec_ddv',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Numéro de titre de recette'),
            preserve_default=False,
        ),
    ]
