# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 09:44
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.models.tables
import app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20190122_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tatelierspgredossierpgre',
            name='id_atel_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAtelierPgre'),
        ),
        migrations.AlterField(
            model_name='tatelierspgredossierpgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre'),
        ),
        migrations.AlterField(
            model_name='tavancementpgre',
            name='ordre_av_pgre',
            field=models.PositiveIntegerField(default=9999, verbose_name='Ordre (liste déroulante)'),
        ),
        migrations.AlterField(
            model_name='tcontroledossierpgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='chem_pj_doss_pgre',
            field=models.FileField(blank=True, default='', upload_to=app.models.tables.TDossierPgre.set_chem_pj_doss_pgre_upload_to, validators=[app.validators.val_fich_pdf], verbose_name='Insérer la fiche action <span class="field-complement">(fichier PDF)</span>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='comm_doss_pgre',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_av_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAvancementPgre', verbose_name="État d'avancement"),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_doss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.TDossier'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_ic_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TInstanceConcertationPgre', verbose_name='Instance de concertation'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_nat_doss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TNatureDossier', verbose_name="Nature de l'action PGRE"),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='id_pr_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TPrioritePgre', verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='int_doss_pgre',
            field=models.CharField(max_length=255, verbose_name="Intitulé de l'action PGRE"),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='mont_doss_pgre',
            field=app.classes.MFEuroField.Class(decimal_places=2, default=0, max_digits=26, verbose_name="Montant de l'action PGRE"),
        ),
        migrations.AlterField(
            model_name='tdossierpgre',
            name='num_doss_pgre',
            field=models.CharField(max_length=255, unique=True, verbose_name="Numéro de l'action PGRE"),
        ),
        migrations.AlterField(
            model_name='tfacturesdemandeversement',
            name='id_ddv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDemandeVersement'),
        ),
        migrations.AlterField(
            model_name='tfacturesdemandeversement',
            name='id_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TFacture'),
        ),
        migrations.AlterField(
            model_name='tinstancesconcertationpgreatelierpgre',
            name='id_atel_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAtelierPgre'),
        ),
        migrations.AlterField(
            model_name='tinstancesconcertationpgreatelierpgre',
            name='id_ic_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TInstanceConcertationPgre'),
        ),
        migrations.AlterField(
            model_name='tmoadossierpgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre'),
        ),
        migrations.AlterField(
            model_name='tmoadossierpgre',
            name='id_org_moa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TMoa'),
        ),
    ]
