# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 09:55
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20190122_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tavancementpgretraces',
            options={'ordering': ['id_trace']},
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='comm_ss_act',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='desc_ss_act',
            field=models.TextField(blank=True, default='', verbose_name='Descriptif'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tdossierssaction',
            name='mont_ss_action_pgre',
            field=app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='descr_ph_pgre',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='id_doss_pgre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TDossierPgre'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='id_ppv_ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TPeriodePriseVuePhoto', verbose_name='Période de prise de vue'),
        ),
        migrations.AlterField(
            model_name='tphotopgre',
            name='int_ph_pgre',
            field=models.CharField(max_length=255, verbose_name='Intitulé de la photo'),
        ),
    ]
