# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 11:17
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.classes.MFPercentField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20190122_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='VFinancement',
            fields=[
                ('vfin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_fin_elig_fin', models.DateField(blank=True, null=True)),
                ('mont_ddv_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_part_fin', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_rad', app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True)),
                ('pourc_glob_fin', app.classes.MFPercentField.Class(decimal_places=3, max_digits=6)),
                ('n_org_fin', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'ordering': ['n_org_fin'],
                'db_table': 'v_financement',
            },
        ),
        migrations.CreateModel(
            name='VSuiviDossier',
            fields=[
                ('id_doss', models.IntegerField(primary_key=True, serialize=False)),
                ('est_ttc_doss', models.BooleanField()),
                ('int_doss', models.TextField()),
                ('mont_aven_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_fact_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_part_fin_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_prest_doss_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_rae', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_raf', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_suppl_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_tot_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_tot_prest_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('num_axe_compl', models.TextField(blank=True)),
                ('tx_engag_doss', app.classes.MFPercentField.Class(decimal_places=3, max_digits=6)),
                ('tx_real_doss', app.classes.MFPercentField.Class(decimal_places=3, max_digits=6)),
                ('type_mont_doss', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'v_suivi_dossier',
            },
        ),
        migrations.CreateModel(
            name='VSuiviPrestationsDossier',
            fields=[
                ('id_prest_doss', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('mont_aven_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Somme @ht_ttc@ des avenants')),
                ('mont_ht_fact_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Somme HT des factures émises')),
                ('mont_ttc_fact_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Somme TTC des factures émises')),
                ('mont_prest_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('mont_raf', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Reste à facturer @ht_ttc@')),
                ('mont_tot_prest_doss', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Montant @ht_ttc@ total (avenants compris)')),
                ('nb_aven', models.IntegerField(verbose_name="Nombre d'avenants")),
                ('nb_fact', models.IntegerField(verbose_name='Nombre de factures')),
            ],
            options={
                'managed': False,
                'db_table': 'v_suivi_prestations_dossier',
            },
        ),
    ]
