# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 12:09
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_vprestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDemandeVersement',
            fields=[
                ('id_ddv', models.IntegerField(primary_key=True, serialize=False)),
                ('map_ht_ddv', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('map_ttc_ddv', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
            ],
            options={
                'db_table': 'v_demande_versement',
                'managed': False,
                'ordering': ['id_ddv'],
            },
        ),
        migrations.AlterModelOptions(
            name='vsuiviprestationsdossier',
            options={'managed': False, 'ordering': ['id_prest__id_org_prest', 'id_prest__dt_notif_prest', 'id_prest__int_prest']},
        ),
    ]
