# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-22 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20190122_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarretesdossier',
            options={'ordering': ['id_type_decl'], 'verbose_name': 'T_ARRETES_DOSSIER', 'verbose_name_plural': 'T_ARRETES_DOSSIER'},
        ),
        migrations.AlterModelOptions(
            name='vdemandeversement',
            options={'managed': False, 'ordering': ['id_org_fin__n_org']},
        ),
        migrations.AlterModelManagers(
            name='tutilisateur',
            managers=[
            ],
        ),
    ]
