# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_auto_20190122_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tphoto',
            options={'ordering': ['id_ppv_ph__ordre_ppv_ph', 'dt_pv_ph'], 'verbose_name': 'T_PHOTO', 'verbose_name_plural': 'T_PHOTO'},
        ),
        migrations.AlterModelOptions(
            name='tphotopgre',
            options={'ordering': ['id_ppv_ph__ordre_ppv_ph', 'dt_pv_ph_pgre'], 'verbose_name': 'T_PHOTO_PGRE', 'verbose_name_plural': 'T_PHOTO_PGRE'},
        ),
        migrations.AddField(
            model_name='tdossier',
            name='num_oper_budg_doss',
            field=models.CharField(blank=True, max_length=255, verbose_name="Numéro d'opération budgétaire"),
        ),
    ]
