# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-01-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20190124_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFicheVie',
            fields=[
                ('id_fdv', models.AutoField(primary_key=True, serialize=False)),
                ('d_fdv', models.DateField(verbose_name='Date')),
                ('lib_fdv', models.CharField(max_length=255, verbose_name='Événement')),
                ('comm_fdv', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'db_table': 't_fiche_vie',
                'ordering': ['-d_fdv'],
            },
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='id_av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TAvancement', verbose_name='\n        État d\'avancement <span class="field-complement">(un dossier est en cours dès que le maître d\'ouvrage a pris la\n        délibération)</span>\n        '),
        ),
        migrations.AddField(
            model_name='tfichevie',
            name='id_doss',
            field=models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.CASCADE, to='app.TDossier'),
        ),
    ]
