# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-06-03 11:28
from __future__ import unicode_literals

import app.models.tables
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20190125_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfichevie',
            name='chem_pj_fdv',
            field=models.FileField(blank=True, upload_to=app.models.tables.TFicheVie.set_chem, validators=[app.validators.val_fich_pdf], verbose_name='Insérer la pièce jointe. '),
        ),
    ]
