# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-18 08:46
from __future__ import unicode_literals

import app.models.tables
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_tfichevie_chem_pj_fdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taction',
            name='int_act',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Intitulé'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxe',
            name='int_axe',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='tfichevie',
            name='chem_pj_fdv',
            field=models.FileField(blank=True, upload_to=app.models.tables.TFicheVie.set_chem, verbose_name='Insérer la pièce jointe. '),
        ),
        migrations.AlterField(
            model_name='tsousaxe',
            name='int_ss_axe',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intitulé'),
        ),
    ]
