# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-18 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20200318_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrdreService',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('comm_os', models.TextField(blank=True, verbose_name='Commentaire')),
                ('d_emiss_os', models.DateField(verbose_name="Date d'émission")),
                ('num_os', models.CharField(max_length=255, verbose_name="Numéro de l'ordre de service")),
                ('obj_os', models.CharField(max_length=255, verbose_name='Objet')),
                ('id_doss', models.ForeignKey(db_column='id_doss', on_delete=django.db.models.deletion.CASCADE, to='app.TDossier')),
                ('id_prest', models.ForeignKey(db_column='id_prest', on_delete=django.db.models.deletion.CASCADE, to='app.TPrestation')),
            ],
            options={
                'db_table': 't_ordre_service',
            },
        ),
    ]
