# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_tordreservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tordreservice',
            options={'ordering': ['num_os']},
        ),
        migrations.AlterField(
            model_name='tordreservice',
            name='id_prest',
            field=models.ForeignKey(db_column='id_prest', on_delete=django.db.models.deletion.CASCADE, to='app.TPrestation', verbose_name='Prestation'),
        ),
    ]
