# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-24 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20200318_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTypeOrdreService',
            fields=[
                ('id_type_os', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type_os', models.CharField(max_length=255, verbose_name='Nom')),
                ('ordre_type_os', models.PositiveIntegerField(default=9999, verbose_name='Ordre (liste déroulante)')),
            ],
            options={
                'verbose_name': 'T_TYPE_ORDRE_SERVICE',
                'db_table': 't_type_ordre_service',
                'ordering': ['ordre_type_os', 'nom_type_os'],
                'verbose_name_plural': 'T_TYPE_ORDRE_SERVICE',
            },
        ),
    ]
