# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-24 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_ttypeordreservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tordreservice',
            name='duree_w_os',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée travaillée (en nombre de jours ouvrés)'),
        ),
        migrations.AddField(
            model_name='tordreservice',
            name='id_type_os',
            field=models.ForeignKey(db_column='id_type_os', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.TTypeOrdreService', verbose_name="Type de l'ordre de service"),
            preserve_default=False,
        ),
    ]
