# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-24 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20200324_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tordreservice',
            options={'ordering': ['d_emiss_os', 'id_type_os']},
        ),
    ]
