# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-24 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20200324_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='tprestationsdossier',
            name='duree_prest_doss',
            field=models.PositiveIntegerField(default=0, verbose_name='Durée de la prestation (en nombre de jours ouvrés)'),
        ),
    ]
