# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20200904_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAcpFinDdsCdg',
            fields=[
                ('acpfinddscdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('acpfinddscdg_com', models.TextField(blank=True, null=True)),
                ('acp_id', models.ForeignKey(db_column='acp_id', on_delete=django.db.models.deletion.CASCADE, to='app.TAvisCp')),
            ],
            options={
                'db_table': 't_acpfinddscdg',
            },
        ),
        migrations.CreateModel(
            name='TCDGemapiCdg',
            fields=[
                ('cdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('cdg_com', models.TextField(blank=True, null=True)),
                ('cdg_date', models.DateField()),
            ],
            options={
                'db_table': 't_cdgemapi_cdg',
                'ordering': ['-cdg_date'],
            },
        ),
        migrations.CreateModel(
            name='TDdsCdg',
            fields=[
                ('ddscdg_id', models.AutoField(primary_key=True, serialize=False)),
                ('ddscdg_pdf_valide', models.BooleanField(default=True)),
                ('cdg_id', models.ForeignKey(db_column='cdg_id', on_delete=django.db.models.deletion.CASCADE, to='app.TCDGemapiCdg')),
                ('dds_id', models.ForeignKey(db_column='dds_id', on_delete=django.db.models.deletion.CASCADE, to='app.TDossier')),
            ],
            options={
                'db_table': 't_ddscdg',
            },
        ),
        migrations.AddField(
            model_name='tacpfinddscdg',
            name='ddscdg_id',
            field=models.ForeignKey(db_column='ddscdg_id', on_delete=django.db.models.deletion.CASCADE, to='app.TDdsCdg'),
        ),
        migrations.AddField(
            model_name='tacpfinddscdg',
            name='fin_id',
            field=models.ForeignKey(db_column='fin_id', on_delete=django.db.models.deletion.CASCADE, to='app.TFinanceur'),
        ),
    ]
