# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-02 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20210201_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcdgemapicdg',
            options={'ordering': ['-cdg_date'], 'verbose_name': 'T_CDGEMAPI_CDG', 'verbose_name_plural': 'T_CDGEMAPI_CDG'},
        ),
        migrations.AddField(
            model_name='tddscdg',
            name='acp_id',
            field=models.ForeignKey(db_column='acp_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.TAvisCp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tcdgemapicdg',
            name='cdg_com',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='tcdgemapicdg',
            name='cdg_date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
