# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-02 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20210202_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcdgemapicdg',
            name='dds',
            field=models.ManyToManyField(through='app.TDdsCdg', to='app.TDossier'),
        ),
    ]
