# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-02 11:39
from __future__ import unicode_literals

import app.models.tables
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_tcdgemapicdg_dds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tacpfinddscdg',
            options={'verbose_name': 'T_ACPFINDDSCDG', 'verbose_name_plural': 'T_ACPFINDDSCDG'},
        ),
        migrations.AlterModelOptions(
            name='tddscdg',
            options={'ordering': ['-cdg_id', 'dds_id'], 'verbose_name': 'T_DDSCDG', 'verbose_name_plural': 'T_DDSCDG'},
        ),
        migrations.AddField(
            model_name='tfinanceur',
            name='init_acpfinddscdg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tacpfinddscdg',
            name='acp_id',
            field=models.ForeignKey(db_column='acp_id', on_delete=django.db.models.deletion.CASCADE, to='app.TAvisCp', verbose_name='Avis'),
        ),
        migrations.AlterField(
            model_name='tacpfinddscdg',
            name='acpfinddscdg_com',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='tacpfinddscdg',
            name='fin_id',
            field=models.ForeignKey(db_column='fin_id', on_delete=django.db.models.deletion.CASCADE, to='app.TFinanceur', verbose_name='Financeur'),
        ),
        migrations.AlterField(
            model_name='tddscdg',
            name='acp_id',
            field=models.ForeignKey(blank=True, db_column='acp_id', default=app.models.tables.TDdsCdg.acp_id_default, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TAvisCp', verbose_name='Avis du comité de programmation - CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tddscdg',
            name='cdg_id',
            field=models.ForeignKey(db_column='cdg_id', on_delete=django.db.models.deletion.CASCADE, to='app.TCDGemapiCdg', verbose_name='CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tddscdg',
            name='dds_id',
            field=models.ForeignKey(db_column='dds_id', on_delete=django.db.models.deletion.CASCADE, to='app.TDossier', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='tddscdg',
            name='ddscdg_pdf_valide',
            field=models.BooleanField(default=True, verbose_name='Le plan de financement prévisionnel est-il validé ?'),
        ),
    ]
