# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-02 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_tfindds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TFinDds',
        ),
        migrations.CreateModel(
            name='FinDds',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('app.tdossier',),
        ),
    ]
