# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20210202_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='findds',
            options={'verbose_name': 'FINDDS', 'verbose_name_plural': 'FINDDS'},
        ),
        migrations.AlterField(
            model_name='tcdgemapicdg',
            name='cdg_date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='num_doss',
            field=models.CharField(max_length=255, unique=True, verbose_name='Numéro du dossier'),
        ),
    ]
