# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_auto_20210203_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdossier',
            name='dt_av_cp_doss',
        ),
        migrations.RemoveField(
            model_name='tdossier',
            name='id_av_cp',
        ),
    ]
