# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_auto_20210203_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tacpfinddscdg',
            name='acpfinddscdg_com',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
            preserve_default=False,
        ),
    ]
