# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_auto_20210203_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tacpfinddscdg',
            options={'ordering': ('fin_id',), 'verbose_name': 'T_ACPFINDDSCDG', 'verbose_name_plural': 'T_ACPFINDDSCDG'},
        ),
        migrations.AddField(
            model_name='tdossier',
            name='dt_depot_doss',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dépôt du dossier'),
        ),
    ]
