# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_auto_20210203_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdossier',
            name='priorite_doss',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], max_length=2, verbose_name='Priorité du dossier'),
        ),
    ]
