# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_tdossier_priorite_doss'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tddscdg',
            unique_together=set([('cdg_id', 'dds_id')]),
        ),
    ]
