# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_auto_20210203_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tddscdg',
            name='cdg_id',
            field=models.ForeignKey(db_column='cdg_id', on_delete=django.db.models.deletion.CASCADE, to='app.TCDGemapiCdg', verbose_name='Date du comité de programmation - CD GEMAPI'),
        ),
    ]
