# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_auto_20210203_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfinancement',
            name='dt_decision_aide_fin',
            field=models.DateField(blank=True, null=True, verbose_name='\n        Date de la décision d\'aide <span class="field-complement">(JJ/MM/AAAA)</span>\n        '),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='annee_prev_doss',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année prévisionnelle d'engagement du dossier"),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='dt_depot_doss',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dépôt du dossier <span class="field-complement">(JJ/MM/AAAA)</span>'),
        ),
    ]
