# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_auto_20210203_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tprestationsdossier',
            name='seq_os_prest_doss',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
