# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_tprestationsdossier_seq_os_prest_doss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tordreservice',
            name='num_os',
            field=models.IntegerField(verbose_name="Numéro de l'ordre de service"),
        ),
    ]
