# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_auto_20210203_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tavenant',
            name='duree_aven',
            field=models.PositiveIntegerField(default=0, verbose_name="Durée de l'avenant (en nombre de jours ouvrés)"),
        ),
    ]
