# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-04 08:26
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_tfacture_dt_emiss_fact'),
    ]

    operations = [
        migrations.CreateModel(
            name='VFacture',
            fields=[
                ('id_fact', models.IntegerField(primary_key=True, serialize=False)),
                ('mont_tva_fact', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
            ],
            options={
                'managed': False,
                'db_table': 'v_facture',
            },
        ),
    ]
