# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0083_auto_20210205_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdossier',
            name='est_autofin',
            field=models.BooleanField(default=False, verbose_name='Le dossier est-il en autofinancement ?'),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='est_pec_ds_bilan',
            field=models.BooleanField(default=False, verbose_name='\n        Le dossier doit-il être pris en compte dans les bilans de\n        programmation ? <span class="field-complement">(si et seulement\n        si non-accordé en comité de programmation - CD GEMAPI)</span>\n        '),
        ),
    ]
