# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_auto_20210208_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='est_autofin_doss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='est_pec_ds_bilan_doss',
            field=models.BooleanField(default=False),
        ),
    ]
