# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-10 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_auto_20210208_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tddscdg',
            name='ddscdg_pdf_valide',
        ),
        migrations.AddField(
            model_name='tddscdg',
            name='ddscdg_pdf_modifie',
            field=models.BooleanField(default=False, verbose_name='Le plan de financement a-t-il été modifié pendant le CD GEMAPI ?'),
        ),
    ]
