# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-11 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_auto_20210210_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tfinanceur',
            name='init_acpfinddscdg',
        ),
    ]
