# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-02-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_tprogramme_bilan_detaille_progr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tprogramme',
            name='bilan_detaille_progr',
            field=models.BooleanField(default=False, verbose_name="\n        Le bilan du programme doit-il être détaillé au niveau du maître\n        d'ouvrage ?\n        "),
        ),
    ]
