# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-04-12 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_auto_20210225_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tprogramme',
            name='bilan_detaille_progr',
        ),
    ]
