# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-05-19 09:35
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.classes.MFPercentField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_remove_tprogramme_bilan_detaille_progr'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdossier',
            name='duree_amor_ppi_doss',
            field=models.IntegerField(blank=True, null=True, verbose_name="Durée d'amortissement (en années)"),
        ),
        migrations.AddField(
            model_name='tdossier',
            name='tx_tva_doss',
            field=app.classes.MFPercentField.Class(decimal_places=3, default=20, max_digits=6, verbose_name='Taux de TVA du dossier (en %)'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_doss',
            field=app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Montant[ht_ou_ttc] du dossier présenté au CD GEMAPI'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='mont_suppl_doss',
            field=app.classes.MFEuroField.Class(decimal_places=2, default=0, max_digits=26, verbose_name='Dépassement[ht_ou_ttc] du dossier'),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='priorite_doss',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=2, verbose_name='Priorité du dossier'),
        ),
    ]
