# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-05-20 08:35
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0093_auto_20210519_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPlanPluriannuelInvestissementPPI',
            fields=[
                ('ppi_id', models.AutoField(primary_key=True, serialize=False)),
                ('ppi_an', models.IntegerField(verbose_name='Année du PPI')),
                ('ppi_budget_an_dps_ttc', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Dépenses TTC (en €)')),
                ('ppi_budget_an_vsm_previ', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Versements prévisionnels (en €)')),
                ('ppi_ntr_dps', models.TextField(blank=True, verbose_name='Nature de la dépense')),
                ('ppi_real_an_pcdt_dps_ttc', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Dépenses TTC (en €)')),
                ('ppi_real_an_pcdt_vsm_previ', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Versements prévisionnels (en €)')),
                ('dds_id', models.ForeignKey(db_column='dds_id', on_delete=django.db.models.deletion.CASCADE, to='app.TDossier')),
            ],
            options={
                'db_table': 't_plan_pluriannuel_investissement_ppi',
                'ordering': ['ppi_an', 'dds_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tplanpluriannuelinvestissementppi',
            unique_together=set([('ppi_an', 'dds_id')]),
        ),
    ]
