# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-05-20 11:39
from __future__ import unicode_literals

import app.classes.MFEuroField
import app.classes.MFPercentField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0095_tprospectiveannuelleppipap'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPpi',
            fields=[
                ('ppi_id', models.OneToOneField(db_column='ppi_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.TPlanPluriannuelInvestissementPpi')),
                ('pap_dps_eli_fctva_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Bilan des dépenses éligibles FCTVA (en €)')),
                ('ppi_dps_ttc_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Bilan des dépenses TTC (en €)')),
                ('ppi_vsm_previ_sum', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26, verbose_name='Bilan des subventions (en €)')),
                ('ppi_tx_eli_fctva_moyen', app.classes.MFPercentField.Class(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name="Taux d'éligibilité FCTVA moyen (en %)")),
            ],
            options={
                'managed': False,
                'db_table': 'v_ppi',
            },
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
