# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-05-31 09:24
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0099_auto_20210526_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdossier',
            name='duree_amor_ppi_doss',
            field=models.IntegerField(blank=True, help_text='Si les études/travaux/biens acquis sont amortissables sur votre syndicat', null=True, verbose_name="Durée d'amortissement (en années)"),
        ),
        migrations.AlterField(
            model_name='tdossier',
            name='priorite_doss',
            field=models.CharField(blank=True, choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], help_text='P1 = ne peut être décalé/reporté - P2 = peut être décalé de 2/3 ans - P3 = peut être décalé de 4/5 ans - P4 = peut être abandonné', max_length=2, verbose_name='Priorité du dossier'),
        ),
        migrations.AlterField(
            model_name='tplanpluriannuelinvestissementppi',
            name='ppi_budget_an_dps_ttc',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Dépenses inscrites sur le BP de l'année du PPI, soit en RAR, soit en nouvelles propositions", max_digits=26, verbose_name='Dépenses TTC (en €)'),
        ),
        migrations.AlterField(
            model_name='tplanpluriannuelinvestissementppi',
            name='ppi_budget_an_vsm_previ',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Subventions inscrites sur le BP de l'année du PPI, soit en RAR, soit en nouvelles propositions", max_digits=26, verbose_name='Versements prévisionnels (en €)'),
        ),
        migrations.AlterField(
            model_name='tplanpluriannuelinvestissementppi',
            name='ppi_ntr_dps',
            field=models.TextField(blank=True, help_text='Peut servir à votre remplissage si vous souhaitez dissocier les dépenses éligibles/non éligibles au FCTVA ou à indiquer des travaux en régie (définition comptable)', verbose_name='Nature de la dépense'),
        ),
        migrations.AlterField(
            model_name='tplanpluriannuelinvestissementppi',
            name='ppi_real_an_pcdt_dps_ttc',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Dépenses réalisées à la clôture du CA de l'année précédente du PPI (hors RAR)", max_digits=26, verbose_name='Dépenses TTC (en €)'),
        ),
        migrations.AlterField(
            model_name='tplanpluriannuelinvestissementppi',
            name='ppi_real_an_pcdt_vsm_previ',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Subventions comptabilisées réalisées à la clôture du CA de l'année précédente du PPI (hors RAR)", max_digits=26, verbose_name='Versements prévisionnels (en €)'),
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='pap_dps_eli_fctva',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text='Remettre les dépenses hors celles non éligibles au FCTVA (déduire notamment les acquisitions foncières estimées)', max_digits=26, verbose_name='Dépenses éligibles FCTVA (en €)'),
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='pap_dps_ttc_rp',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Rythme prévisionnel de réalisation des dépenses qui restent à faire sur l'opération (réaliste au regard des conditions techniques de réalisation)", max_digits=26, verbose_name='Dépenses TTC réelles projetées (en €)'),
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='pap_vsm_previ_rp',
            field=app.classes.MFEuroField.Class(decimal_places=2, help_text="Rythme prévisionnel de perception des subventions qui restent à faire sur l'opération (avances/soldes)", max_digits=26, verbose_name='Versements prévisionnels réels projetés (en €)'),
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
