# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-09-14 15:43
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0102_auto_20210615_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='TProgrammeDetaillePrg',
            fields=[
                ('prg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prg_mnt1', app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True)),
                ('prg_mnt2', app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True)),
                ('prg_mnt3', app.classes.MFEuroField.Class(blank=True, decimal_places=2, max_digits=26, null=True)),
                ('prg_mnt_est_ttc', models.BooleanField()),
                ('prg_nbre_dos', models.IntegerField(blank=True, null=True)),
                ('act_id', models.CharField(max_length=255)),
                ('moa_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': '"hors_public"."t_programme_detaille_prg"',
            },
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
