# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-09-15 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0104_auto_20210914_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tprogrammedetailleprg',
            options={'managed': False, 'verbose_name': "Détail des axes et actions d'un programme d'actions", 'verbose_name_plural': "Détail des axes et actions d'un programme d'actions"},
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
