# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2021-10-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0114_auto_20211020_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tddscdgrestricted',
            options={'verbose_name': 'Dossier présente à un CD GEMAPI (accès restreint)', 'verbose_name_plural': 'Dossiers présentés à un CD GEMAPI (accès restreint)'},
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
