# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-05-23 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_auto_20211020_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfinanceur',
            name='est_princi',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
