# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2022-08-05 09:06
from __future__ import unicode_literals

import app.classes.MFEuroField
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0119_auto_20220805_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='V_DemandeVersement_SyntheseDossierFinanceur',
            fields=[
                ('QRY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DVS_MT_MAP_HT', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('DVS_MT_MAP_TTC', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('DVS_MT_TOTAL_HT', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('DVS_MT_TOTAL_TTC', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('DVS_NB', models.IntegerField()),
                ('VSM_MT_TOTAL_HT', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
                ('VSM_MT_TOTAL_TTC', app.classes.MFEuroField.Class(decimal_places=2, max_digits=26)),
            ],
            options={
                'db_table': 'v_demandeversement_synthesedossierfinanceur',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='tprospectiveannuelleppipap',
            name='ppi_id',
            field=models.ForeignKey(db_column='ppi_id', on_delete=django.db.models.deletion.CASCADE, to='app.TPlanPluriannuelInvestissementPpi'),
        ),
    ]
